version: "3"
services:
  redis4proxypool:
    image: redis:alpine
    container_name: redis4proxypool
  proxypool:
    image: "germey/proxypool:master"
    container_name: proxypool
    ports:
      - "5557:5555"
    restart: always
    # volumes:
    #   - proxypool/crawlers/private:/app/proxypool/crawlers/private
    environment:
      PROXYPOOL_REDIS_HOST: redis4proxypool
      TEST_URL: http://weibo.cn
      REDIS_KEY: proxies:weibo
